version: '3.1'

services:

  web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./site.conf:/etc/nginx/conf.d/site.conf
        - ./conf.d:/etc/nginx/conf.d/
        - ./code:/code
        - ./logs/nginx:/var/log/nginx
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    links:
        - mysql
    volumes:
        - ./code:/code

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tellariondocker
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql